/**
 * @file
 *
 * Utilities for retrieving GLSL or CL source strings that have been baked
 * into the executable. The corresponding C++ file is generated by
 * @c source2cpp.py.
 */

#ifndef SOURCE2CPP_H
#define SOURCE2CPP_H

#include <common/debug_unordered_map.h>
#include <common/debug_string.h>

/**
 * Retrieve the map from source filenames to source content.
 */
const uts::unordered_map<uts::string, uts::string> &getSourceMap();

/**
 * Retrieve a source by filename.
 *
 * @param filename     The original filename, with path information excluded
 * @throw std::invalid_argument If the source does not exist
 */
const uts::string &getSource(const uts::string &filename);

#endif /* !SOURCE2CPP_H */
